### PR TITLE
Fix #7 test HDAP store

### LINKED ISSUE #7: Add tests for HDAP store
The HDAP store needs automated tests to avoid regressions.

### PR DESCRIPTION
**Pull request by markcraig**
This adds basic tests for the HDAP store.

```
npm run test

> hdap-demo@0.0.0 test
> vitest


 DEV  v1.4.0 /Users/mark/Downloads/hdap-demo

 ✓ src/tests/hdap.test.js (18) 509ms
 ✓ src/tests/hdapStore.test.js (3)

 Test Files  2 passed (2)
      Tests  21 passed (21)
   Start at  15:54:31
   Duration  1.05s (transform 122ms, setup 0ms, collect 198ms, tests 660ms, environment 466ms, prepare 247ms)


 PASS  Waiting for file changes...
       press h to show help, press q to quit
```

### CODE REVIEW

File: src/store/hdap.js [hunk 1]
```diff
@@ -26,7 +27,7 @@ export const useHdapStore = defineStore('hdapStore', () => {
         currentJwt.value = ''
         friendlyUserName.value = ''
         message.value = (showMessage) ? 'Session expired' : ''
-        router.push('/')
+        if (!skipForTests) router.push('/')
```
Comment (markcraig) [inline src/store/hdap.js]: This line is in the wrong place, I realize.

It's only when the user actively chooses to log out that the application should return to the home page. If you're session times out while you're in the middle of an update, you should be able to log in and continue without interruption.

Comment (markcraig) [reply src/store/hdap.js]: Fixed in my copy

**Comment by markcraig** [comment]
Going to merge this one as a basis for testing
